### ISSUE TITLE
Got this error

### ISSUE THREAD

**Issue by Thevextrion** [Kaseaa/bahaar-wave-practice#2]
[20:36:49.540] [command] ERROR: Error: [dispatch] write: failed to generate S_ACTION_STAGE<8>:
Error: version 8 of message (name: "S_ACTION_STAGE", code: 38320) is outdated and cannot be used anymore
    at Dispatch.write (C:\Users\evaaaa\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:330:23)
    at Module.send (C:\Users\evaaaa\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\module.js:175:38)
    at String.<anonymous> (C:\Users\evaaaa\AppData\Local\Programs\TeraToolbox\mods\bahaar-wave-practice-master\index.js:102:30)
    at CommandBase.exec (C:\Users\evaaaa\AppData\Local\Programs\TeraToolbox\mods\command\index.js:196:16)
    at hookCommand (C:\Users\evaaaa\AppData\Local\Programs\TeraToolbox\mods\command\index.js:71:31)
    at Object.callback (C:\Users\evaaaa\AppData\Local\Programs\TeraToolbox\mods\command\index.js:81:29)
    at Dispatch.handle (C:\Users\evaaaa\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\connection\dispatch\index.js:443:45)
    at Socket.<anonymous> (C:\Users\evaaaa\AppData\Local\Programs\TeraToolbox\node_modules\tera-network-proxy\lib\clients\RealClient.js:38:45)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)

**Comment by Thevextrion** [comment]
can you update it pls ?

**Comment by Thevextrion** [comment]
i can summon him but he doesnt do the wave

**Comment by Kasea** [comment]
Go yell at Caali

**Comment by Xertyn** [comment]
Error: version 8 of message (name: "S_ACTION_STAGE", code: 38320) is outdated and cannot be used anymore - well, it works with version 9 too.
I forked this module and fixed it to use version 9 instead. Just a few bytes difference...

**Comment by unlimitedgtx** [comment]
@Xertyn Can yu update urs maybe? Cant use it

**Comment by Xertyn** [comment]
@unlimitedgtx 
[https://github.com/Xertyn/bahaar-wave-practice](https://github.com/Xertyn/bahaar-wave-practice) - my fork, it still works for me

Just in case, be sure to use the latest OPCode files from [here](https://github.com/PsykoDev/Full-Opcode-Tera-EU-NA)  and put it in the right folder in your toolbox.
